sudo: required
services: 
  - docker

before_install:
  - docker build -t sandeepsangole/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true sandeepsangole/frontend

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-066733044942"
  bucket_path: "udemy-docker-react"
  on:
    branch: main